### ISSUE TITLE
Build Error - Glog

### ISSUE THREAD

**Issue by jastion** [CogRob/gcloud_speech#21]
Hi,

I was trying to use your github repo but encountered build errors during catkin_make
It seems to be missing a glog/logging.h file.
Could you provide the missing file or did I miss a step somewhere?
Thank You,

In file included from /home/user/catkin_ws/src/gcloud_speech/gcloud_speech_utils/src/workspace/cogrob/cloud/speech/record_audio.cc:38:0:
/home/user/catkin_ws/src/gcloud_speech/gcloud_speech_utils/src/workspace/third_party/glog.h:30:26: fatal error: glog/logging.h: No such file or directory
compilation terminated.

**Comment by jastion** [comment]
fixed
needed to install libgoogle-glog-dev package
suggest adding to this to Readme?

System: Ubuntu 16.04

**Comment by BillWSY** [comment]
https://github.com/CogRob/gcloud_speech/blob/d29fe0b409aaf4c3566aed634b6385481c7931ef/gcloud_speech/package.xml#L15
